# This setup creates a persistent Grafana service accessible at http://localhost:3000.

version: "3.8"
services: 
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped # unless-stopped policy keeps the service running continuously unless manually stopped.
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      # The grafana-storage volume is a named Docker volume, and it is stored in Docker's default volume directory on your host system. 
      # The exact path to this storage depends on your Docker installation
volumes: 
  grafana-storage: {} # The empty braces {} indicate that no additional configuration is provided; Docker will manage this volume automatically.
