global:
  scrape_interval: 15s  # Sets the global scraping interval to 15 seconds

scrape_configs:
  - job_name: "prometheus"  # Job to scrape the Prometheus server itself
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "elzim"  # Example: job for the elzim server
    static_configs:
      - targets: ['192.168.68.109:9100']
